name: 🐞 Bug report
description: "Report a bug or something that is otherwise not working as expected."
labels: ["bug"]

body:
  - type: checkboxes
    id: diagnostics
    attributes:
      label: Diagnostic Checklist
      description: "Check these common causes to rule out basic configuration or setup issues."
      options:
        - label: "MyDyson [iPhone](https://apps.apple.com/gb/app/mydyson/id993135524) or [Android](https://play.google.com/store/apps/details?id=com.dyson.mobile.android) app can control the appliance."
        - label: "Searched for [previously reported issues](https://github.com/thoukydides/matterbridge-dyson-robot/issues?q=is%3Aissue) and found none."
    validations:
      required: false
      
  - type: textarea
    id: description
    attributes:
      label: Description of Issue
      description: "Provide a clear and concise description of the bug."
      placeholder: |
        Describe what is going wrong, the symptoms, the frequency, and any recent changes.
        What did you expect to happen? What actually happened?
    validations:
      required: true
    
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: "Provide a step-by-step description of how to reproduce the issue."
      placeholder: |
        Steps to reproduce:
        1. ...
        2. ...
    validations:
      required: true
  
  - type: input
    id: version
    attributes:
      label: Plugin Version
      description: "State the plugin version exhibiting the bug. If not using the latest version, please update before reporting."
    validations:
      required: true
      
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Describe the software environment being used to run this plugin. Include:
        - Operating System type and version (output of `lsb_release -d` or `cat /etc/os-release` on Linux)
        - Node.js version (output of `node -v` or reported in Matterbridge frontend)
        - Matterbridge version (output of `npm -g ls matterbridge` or reported in Matterbridge frontend)
      placeholder: |
        - OS: e.g. Ubuntu 24.04.1 LTS or macOS Ventura 13.5
        - Node: e.g. v22.15.0
        - Matterbridge: e.g. 3.0.0
    validations:
      required: true

  - type: input
    id: appliance
    attributes:
      label: Dyson Appliance(s)
      description: |
        Specify which Dyson appliance(s) the issue relates to. You can find the model name and number behind the clear bin on robot vacuums, or on the base of air treatment devices.
      placeholder: "e.g. Dyson 360 Eye RB01"
    validations:
      required: true
      
  - type: input
    id: mattercontroller
    attributes:
      label: Matter Controller(s)
      description: "Provide details of the Matter controller(s) being used, including their versions."
      placeholder: "e.g. Apple Home iOS 18.4, Amazon Alexa, Google Home, Samsung SmartThings, Home Assistant 2025.4.3, etc."
    validations:
      required: false
      
  - type: textarea
    id: log
    attributes:
      label: Log File
      description: |
        Provide relevant Matterbridge logs, either pasted below or attached as a text file. Do NOT use a screenshot. Replace sensitive information (access tokens, etc) with `REDACTED`. Logs are most useful when they are complete; include the full output around the error message and do not omit any lines.

        Enable and capture appropriate extra debug:
        
        - **For Plugin Debug Logging** (enable for most issues):
          - In Matterbridge frontend: *Home* > *Plugins* > *matterbridge-dyson-robot* > ⚙️ > *debug* > ✅
            - Or in the `matterbridge-dyson-robot.config.json` file: `"debug": true`
          - View the log file directly (e.g. `journalctl -u matterbridge.service -n 1000 -f --output cat`); the Matterbridge frontend normally filters out debug messages.
          
        - **For Dyson MQTT Logging (enable for any Dyson interoperability issues)**:
          - In Matterbridge frontend: *Home* > *Plugins* > *matterbridge-dyson-robot* > ⚙️ > *Enable advanced debug option* > *Log MQTT Payloads as JSON*
            - Or in the `matterbridge-dyson-robot.config.json` file: `"debugFeatures": ["Log MQTT Payloads as JSON"]`
          
        - **For Matterbridge Logging**:
          - In Matterbridge frontend: *Settings* > *Matterbridge settings* > *Logger level* > *Debug*.
            - Or add `-logger debug` to the `matterbridge` command line.
          
        - **For Matter Logging**:
          - In Matterbridge frontend: *Settings* > *Matter settings* > *Logger level* > *Debug*.
            - Or add `-matterlogger debug` to the `matterbridge` command line.
        
        The additional debug information in the logs will provide more context for resolving your issue.
      placeholder: |
        Paste the logs...
      render: shell
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: "Provide your `matterbridge-dyson-robot.config.json` (if relevant). This is optional but highly recommended. Replace sensitive information (API Key and Access/Refresh Tokens) with `REDACTED`."
      placeholder: "Paste configuration..."
      render: json
    validations:
      required: false
   
  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: |
        Provide any additional information that might assist with resolving your bug report. This could include links to product web pages, user manuals, screenshots, videos, or anything else relevant. If you have tried workarounds or debugging steps, include them here.

        If the issue relates to an unsupported or recently released Dyson product the use the `opendyson` tool to capture a full MQTT message log whilst exercising as much of the device's functionality as possible, e.g. adjusting every setting of an air purifier or performing a full clean with a robot vacuum:

        - Install `opendyson`, e.g. if `Go` is installed and configured:
          `go install github.com/libdyson-wg/opendyson`
        - Login to your MyDyson account:
          `opendyson login`
        - Identify devices and retrieve their connection credentials:
          `opendyson devices`
        - Capture an MQTT message log:
          `opendyson listen SERIALNUMBER` (with the device's actual serial number substituted)
        - Paste or attach the output of `opendyson devices` and `opendyson listen` here (as text, not a screenshot)
        
        For robot vacuums, also use the Proxyman app to capture the MyDyson app's HTTPS requests:
        
        - Install [Proxyman](https://apps.apple.com/gb/app/proxyman/id1551292695). (The free edition is sufficient; the Proxyman Pro in-app purchases are not required.)
        - Run `Proxyman`, and on its **More** tab:
          - Follow the "How to setup" instructions to install and trust the root certificate.
          - Under **SSL Proxying List** add `appapi.cp.dyson.com` and enable it.
          - Start the VPN. Ensure that `Ready to intercept` is displayed.
        - Launch the MyDyson app.
        - On Proxyman's **Home** tab search for and select `appapi.cp.dyson.com`. Ensure that requests are being captured and decoded.
        - Switch back to the MyDyson app and try all of the robot vacuum's basic functionality, including:
          - Change the power level for an "All areas" clean.
          - Start an "All areas" clean.
          - Change the power level for a zone.
          - Start a clean of a single zone.
          - View the most recent cleaned area map.
        - Return to Proxyman, and click on the cog icon above the list of messages, select **Share**, and then **Save to Files**. This will create a `.proxymanlogv2` file (a Zip archive containing a JSON representation of each captured request). Attach the saved file (not a screenshot) here.
      placeholder: "Any other relevant information..."
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        **Important Notes:**
        - 🐞 Most issues cannot be diagnosed without debug logs - please include them.
        - 🔐 Ensure sensitive information like tokens or passwords are `REDACTED` before sharing.
        - 🔄 Always update to the latest plugin version before reporting bugs.
        - 🧪 This is a personal project, so not all issues may be investigated or resolved. Please do not take it personally.