// Matterbridge plugin for Dyson robot vacuum and air treatment devices
// Copyright © 2026 Alexander Thoukydides

// Mapping of air treatment device fault codes to descriptions
export const DYSON_AIR_FAULT_CODES: Record<string, string> = {
    // GET /v1/support/product-faults/{serial}?locale=en-GB&market=GB&faultCode={code}
    amf1:   'Motor fault',
    amf2:   'Motor fault',
    amf3:   'Motor fault',
    amf4:   'Motor fault',
    amf5:   'Motor fault',
    amf6:   'Motor fault',
    amf7:   'Motor fault',
    amf8:   'Motor fault',
    amf9:   'Fault detected',
    cflr:   '0% filter life remaining',
    cldu:   'Deep clean cycle due',
    cnfg:   'Fault detected',
    com1:   'Motor fault',
    com2:   'Fault detected',
    com3:   'Fault detected',
    com4:   'Motor fault',
    com6:   'Fault detected',
    com7:   'Fault detected',
    com8:   'Fault detected',
    dsts:   'Particle sensor fault',
    etwd:   'Drip tray overflow',
    etws:   'Drip tray overflow while in deep clean',
    filf:   '0% filter life remaining',
    fmco:   'Motor fault',
    fs00:   'Fault detected',
    fs01:   'Fault detected',
    hall:   'Motor fault',
    hamb:   'Heater fault',
    hamp:   'Motor fault',
    hctf:   'Heater fault',
    hflr:   '0% filter life remaining',
    hilc:   'Heater fault',
    hioc:   'Heater fault',
    ht01:   'Heater fault',
    ht02:   'Heater fault',
    ht03:   'Heater fault',
    ht04:   'Heater fault',
    ht05:   'Heater fault',
    ht06:   'Heater fault',
    ht07:   'Heater fault',
    ht08:   'Fault detected',
    ht09:   'Heater fault',
    ht0a:   'Heater fault',
    htri:   'Heater fault',
    hvmi:   'Heater fault',
    ibus:   'Fault detected',
    ilss:   'Fault detected',
    ion1:   'Ioniser fault',
    iuc1:   'Software update failed',
    iuc3:   'Software update failed',
    iuc4:   'Software update failed',
    iuh0:   'Software update failed',
    iuh1:   'Software update failed',
    iuh3:   'Software update failed',
    iuh4:   'Software update failed',
    iup0:   'Software update failed',
    iuu1:   'Software update failed',
    iuu2:   'Software update failed',
    iuu3:   'Software update failed',
    iuu4:   'Software update failed',
    iuw1:   'Software update failed',
    iuw3:   'Software update failed',
    iuw4:   'Software update failed',
    nvmm:   'Hardware memory fault',
    nvmr:   'Hardware memory fault',
    nvmw:   'Hardware memory fault',
    povi:   'Heater fault',
    prot:   'Pump rotor fault',
    psu1:   'Power supply unit fault',
    psu2:   'Power supply unit fault',
    psu3:   'Power supply unit fault',
    sen1:   'Particle sensor fault',
    sen2:   'Organic gas sensor fault',
    sen3:   'Temperature sensor fault',
    sen4:   'Humidity sensor fault',
    sen5:   'Filter air pressure sensor fault',
    sen6:   'Filter not installed',
    sen7:   'Formaldehyde sensor fault',
    sen8:   'Sensor data fault',
    sen9:   'Fan speed sensor fault',
    sena:   'Fan speed sensing error',
    senb:   'Carbon dioxide sensor fault',
    shrt:   'Motor fault',
    so01:   'Find+Follow error',
    so02:   'Find+Follow error',
    stal:   'Motor fault',
    ste1:   'Oscillation disabled',
    ste2:   'Airflow angle disabled',
    stto:   'Motor fault',
    't&hs': 'Temperature and humidity sensor fault',
    tilt:   'Heater fault',
    tnke:   'Tank empty',
    tnkp:   'Tank not detected',
    tosl:   'Tilt angle disabled',
    ui01:   'Display fault',
    ui02:   'Display fault',
    ui03:   'Display fault',
    uled:   'Water pump UV cleaner fault',
    uvc1:   'UV steriliser fault',
    vocs:   'Organic gas sensor fault',
    wdog:   'Fault detected',
    wpmp:   'Unable to humidify',
    // Other fault codes seen in MQTT logs (guessed meanings)
    bosl:   'Breeze oscillation sensor left [unverified]',
    bosr:   'Breeze oscillation sensor right [unverified]',
    com5:   'Fault detected [unverified]',
    com9:   'Fault detected [unverified]',
    coma:   'Fault detected [unverified]',
    fltr:   'Filter replacement warning [unverified]',
    fs02:   'Fault detected [unverified]',
    fs03:   'Fault detected [unverified]',
    fs04:   'Fault detected [unverified]',
    fs05:   'Fault detected [unverified]',
    fs06:   'Fault detected [unverified]',
    fs07:   'Fault detected [unverified]',
    fs08:   'Fault detected [unverified]',
    fs09:   'Fault detected [unverified]',
    fs0a:   'Fault detected [unverified]',
    fs0b:   'Fault detected [unverified]',
    fs0c:   'Fault detected [unverified]',
    fs0d:   'Fault detected [unverified]',
    fs0e:   'Fault detected [unverified]',
    fs0f:   'Fault detected [unverified]',
    htcf:   'Heater fault [unverified]',
    iua1:   'Software update failed [unverified]',
    iua2:   'Software update failed [unverified]',
    iua3:   'Software update failed [unverified]',
    iua4:   'Software update failed [unverified]',
    iuc2:   'Software update failed [unverified]',
    iuh2:   'Software update failed [unverified]',
    iuw0:   'Software update failed [unverified]',
    iuw2:   'Software update failed [unverified]',
    uid1:   'Display fault [unverified]',
    uid2:   'Display fault [unverified]',
    wfcp:   'Wi-Fi communications fault [unverified]',
    wfhb:   'Wi-Fi heartbeat lost [unverified]'
};