name: Build, Lint, and Test
permissions:
  contents: read

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '15 7 * * MON-SAT'
    - cron: '15 7 * * SUN'

jobs:

  call-reusable:
    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x, 22.x, 24.x]
        matterbridge-branch: ['', 'dev']
    uses: ./.github/workflows/build-lint-test-single.yml
    with:
      node-version: ${{ matrix.node-version }}
      matterbridge-branch: ${{ matrix.matterbridge-branch }}
      run-live-tests: ${{ github.event_name != 'schedule' || github.event.schedule == '15 7 * * SUN' }}